### ISSUE TITLE
Error: Failed to save lcovonly coverage

### ISSUE THREAD

**Issue by geoffcorey** [serut/meteor-coverage-app-exemple#13]
Having issues adding code coverage to an existing project and decided to run your example to see what the difference would be.  Turns out it has the exact same issue.

Node    v11.6.0
Meteor 1.8.0.2 
Darwin Kernel Version 18.2.0 (OS/X)

```bash
git clone https://github.com/serut/meteor-coverage-app-exemple.git
cd bare-exemple/
meteor npm run test:unit:coverage
```
Results in
```
TEST_BROWSER_DRIVER=puppeteer COVERAGE=1 COVERAGE_VERBOSE=1 COVERAGE_OUT_HTML=1 COVERAGE_OUT_LCOVONLY=1 COVERAGE_APP_FOLDER=$(pwd)/ meteor test --once --driver-package meteortesting:mocha --raw-logs

[[[[[ Tests ]]]]]

=> Started proxy.
=> Started MongoDB.
Coverage active
Reading custom configuration
[Configuration]  { include: [ '**/*.js' ],
  remap:
   { format:
      [ 'html',
        'clover',
        'cobertura',
        'json',
        'json-summary',
        'lcovonly',
        'teamcity',
        'text',
        'text-summary' ] } }
Loading default configuration: output
Loading default configuration: remapFormat
Coverage configuration:
- IS_COVERAGE_ACTIVE= true
- IS_COVERAGE_VERBOSE= true
- COVERAGE_APP_FOLDER= /Users/gwcorey@us.ibm.com/src/github.com/serut/meteor-coverage-app-exemple/bare-exemple/
.coverage.json values:
- remapFormat= [ 'html',
  'cobertura',
  'clover',
  'json',
  'json-summary',
  'lcovonly',
  'teamcity',
  'text',
  'text-summary' ]
- COVERAGE_EXPORT_FOLDER= ./.coverage

--------------------------------
----- RUNNING SERVER TESTS -----
--------------------------------



  links publications
=> Started your app.

=> App running at: http://localhost:3000/
    links.all
      ✓ sends all links

  links collection
    ✓ insert correctly

  links methods
    ✓ can add a new link

  fake testing the back
    ✓ dumb test
    ✓ should import file


  5 passing (86ms)


--------------------------------
----- RUNNING CLIENT TESTS -----
--------------------------------
HeadlessChrome/73.0.3679.0


  fake testing the front
    ✓ dumb test
    ✓ should import file


  2 passing (52ms)

Meteor-coverage is saving client side coverage to the server. Client js files saved  {"SUCCESS":0,"FAILED":0,"TOTAL":0}
All tests finished!

--------------------------------
SERVER FAILURES: 0
CLIENT FAILURES: 0
--------------------------------
Export code coverage
- Out lcovonly
export coverage using the following format [ lcovonly ] options [ { path: '/Users/gwcorey@us.ibm.com/src/github.com/serut/meteor-coverage-app-exemple/bare-exemple/.coverage',
  verbose: true } ]
Try to remove the content & create the file /Users/gwcorey@us.ibm.com/src/github.com/serut/meteor-coverage-app-exemple/bare-exemple/.coverage/lcov.info
Error: Failed to save lcovonly coverage
    at HTTP.get (packages/meteortesting:mocha/server.handleCoverage.js:37:18)
    at runWithEnvironment (packages/meteor.js:1356:24)
```

**Comment by serut** [comment]
Hello,  
That's pretty akward, as there is a CI platform running well on that project ! 

https://travis-ci.org/serut/meteor-coverage-app-exemple  
https://circleci.com/gh/serut/meteor-coverage-app-exemple  

There is an issue to generate the lcov report, but there is no client coverage collected on your client side too (this is what we should see in your report) : 
```
Meteor-coverage is saving client side coverage to the server. Client js files saved  {"SUCCESS":5,"FAILED":0,"TOTAL":5}
```

Can you try somewhere outside of your home directory ? Maybe it can be related to the `@` in the path to your repository

**Comment by geoffcorey** [comment]
Steps 

```bash
tar cvf bare-example.tgz bare-example/
cd /tmp
tar xvf ~/src/github.com/serut/meteor-coverage-app-exemple/bare-example.tgz
cd bare-example/
meteor npm run test:unit:coverage
```
Result

```

--------------------------------
SERVER FAILURES: 0
CLIENT FAILURES: 0
--------------------------------
Export code coverage
- Out lcovonly
export coverage using the following format [ lcovonly ] options [ { path: '/tmp/bare-exemple/.coverage', verbose: true } ]
Try to remove the content & create the file /tmp/bare-exemple/.coverage/lcov.info
Error: Failed to save lcovonly coverage
    at HTTP.get (packages/meteortesting:mocha/server.handleCoverage.js:37:18)
    at runWithEnvironment (packages/meteor.js:1356:24)
```

**Comment by geoffcorey** [comment]
Node version perhaps?   I see your travis job is running 8.9.1  which is pretty old and I'm running 11.6.0

I just downgraded to LTS v10.15.1 and it still fails.  Maybe up the node version in the Travis job to LTS at the least and see if it replicates my results?

```bash
nvm install --lts
Installing latest LTS version.
Downloading and installing node v10.15.1...
Downloading https://nodejs.org/dist/v10.15.1/node-v10.15.1-darwin-x64.tar.xz...
######################################################################## 100.0%
Computing checksum with shasum -a 256
Checksums matched!
Now using node v10.15.1 (npm v6.4.1)
Creating default alias: default -> lts/* (-> v10.15.1)
geoffreys-mbp:~ gwcorey@us.ibm.com$ cd /tmp/bare-exemple/
geoffreys-mbp:bare-exemple gwcorey@us.ibm.com$ npm run test:unit:coverage

> bare-exemple@ test:unit:coverage /private/tmp/bare-exemple
> TEST_BROWSER_DRIVER=puppeteer COVERAGE=1 COVERAGE_VERBOSE=1 COVERAGE_OUT_HTML=1 COVERAGE_OUT_LCOVONLY=1 COVERAGE_APP_FOLDER=$(pwd)/ meteor test --once --driver-package meteortesting:mocha --raw-logs

[[[[[ Tests ]]]]]

=> Started proxy.
=> Started MongoDB.
Coverage active
Reading custom configuration
[Configuration]  { include: [ '**/*.js' ],
  remap:
   { format:
      [ 'html',
        'clover',
        'cobertura',
        'json',
        'json-summary',
        'lcovonly',
        'teamcity',
        'text',
        'text-summary' ] } }
Loading default configuration: output
Loading default configuration: remapFormat
Coverage configuration:
- IS_COVERAGE_ACTIVE= true
- IS_COVERAGE_VERBOSE= true
- COVERAGE_APP_FOLDER= /tmp/bare-exemple/
.coverage.json values:
- remapFormat= [ 'html',
  'cobertura',
  'clover',
  'json',
  'json-summary',
  'lcovonly',
  'teamcity',
  'text',
  'text-summary' ]
- COVERAGE_EXPORT_FOLDER= ./.coverage

--------------------------------
----- RUNNING SERVER TESTS -----
--------------------------------



  links publications
=> Started your app.

=> App running at: http://localhost:3000/
    links.all
      ✓ sends all links

  links collection
    ✓ insert correctly

  links methods
    ✓ can add a new link

  fake testing the back
    ✓ dumb test
    ✓ should import file


  5 passing (88ms)


--------------------------------
----- RUNNING CLIENT TESTS -----
--------------------------------
HeadlessChrome/73.0.3679.0


  fake testing the front
    ✓ dumb test
    ✓ should import file


  2 passing (56ms)

Meteor-coverage is saving client side coverage to the server. Client js files saved  {"SUCCESS":0,"FAILED":0,"TOTAL":0}
All tests finished!

--------------------------------
SERVER FAILURES: 0
CLIENT FAILURES: 0
--------------------------------
Export code coverage
- Out lcovonly
export coverage using the following format [ lcovonly ] options [ { path: '/tmp/bare-exemple/.coverage', verbose: true } ]
Try to remove the content & create the file /tmp/bare-exemple/.coverage/lcov.info
Error: Failed to save lcovonly coverage
    at HTTP.get (packages/meteortesting:mocha/server.handleCoverage.js:37:18)
    at runWithEnvironment (packages/meteor.js:1356:24)
```

**Comment by serut** [comment]
No, the NPM installed globally is not used while testing a meteor project. Meteor provides its version threw `meteor npm`, so the version used (`meteor npm --version`) will be the same as we both use Meteor 1.8.0.2

I just use that version on travis to get the right setup for chromium,... Let me test on my Ubuntu 18 from scratch to see if it makes a difference

**Comment by serut** [comment]
Everything runs fine on my side : 
```
cd /tmp
git clone https://github.com/serut/meteor-coverage-app-exemple.git
cd meteor-coverage-app-exemple/bare-exemple/
meteor npm install && meteor npm run test:coverage
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated hoek@5.0.4: This version is no longer maintained. Please upgrade to the latest version.
npm WARN deprecated hoek@0.9.1: The major version is no longer supported. Please update to 4.x or newer

> puppeteer@1.12.2 install /tmp/meteor-coverage-app-exemple/bare-exemple/node_modules/puppeteer
> node install.js

Downloading Chromium r624492 - 107.6 Mb [====================] 100% 0.0s 
Chromium downloaded to /tmp/meteor-coverage-app-exemple/bare-exemple/node_modules/puppeteer/.local-chromium/linux-624492
npm notice created a lockfile as package-lock.json. You should commit this file.
added 304 packages from 702 contributors and audited 1043 packages in 42.864s
found 8 moderate severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details

> bare-exemple@ test:coverage /tmp/meteor-coverage-app-exemple/bare-exemple
> meteor npm run test:unit:coverage && meteor npm run test:packages:coverage


> bare-exemple@ test:unit:coverage /tmp/meteor-coverage-app-exemple/bare-exemple
> TEST_BROWSER_DRIVER=puppeteer COVERAGE=1 COVERAGE_VERBOSE=1 COVERAGE_OUT_HTML=1 COVERAGE_OUT_LCOVONLY=1 COVERAGE_APP_FOLDER=$(pwd)/ meteor test --once --driver-package meteortesting:mocha --raw-logs

[[[[[ Tests ]]]]]                             

=> Started proxy.                             
=> Started MongoDB.                           
Coverage active                               
Reading custom configuration
[Configuration]  { include: [ '**/*.js' ],
  remap: 
   { format: 
      [ 'html',
        'clover',
        'cobertura',
        'json',
        'json-summary',
        'lcovonly',
        'teamcity',
        'text',
        'text-summary' ] } }
Loading default configuration: output
Loading default configuration: remapFormat
Coverage configuration:
- IS_COVERAGE_ACTIVE= true
- IS_COVERAGE_VERBOSE= true
- COVERAGE_APP_FOLDER= /tmp/meteor-coverage-app-exemple/bare-exemple/
.coverage.json values:
- remapFormat= [ 'html',
  'cobertura',
  'clover',
  'json',
  'json-summary',
  'lcovonly',
  'teamcity',
  'text',
  'text-summary' ]
- COVERAGE_EXPORT_FOLDER= ./.coverage

--------------------------------
----- RUNNING SERVER TESTS -----
--------------------------------



  links publications
=> Started your app.

=> App running at: http://localhost:3000/
    links.all
      ✓ sends all links

  links collection
    ✓ insert correctly

  links methods
    ✓ can add a new link

  fake testing the back
    ✓ dumb test
    ✓ should import file


  5 passing (416ms)


--------------------------------
----- RUNNING CLIENT TESTS -----
--------------------------------
HeadlessChrome/73.0.3679.0


  fake testing the front
    ✓ dumb test
    ✓ should import file


  2 passing (72ms)

Meteor-coverage is saving client side coverage to the server. Client js files saved  {"SUCCESS":5,"FAILED":0,"TOTAL":5}
All tests finished!

--------------------------------
SERVER FAILURES: 0
CLIENT FAILURES: 0
--------------------------------
Export code coverage
- Out lcovonly
export coverage using the following format [ lcovonly ] options [ { path: '/tmp/meteor-coverage-app-exemple/bare-exemple/.coverage',
  verbose: true } ]
Try to remove the content & create the file /tmp/meteor-coverage-app-exemple/bare-exemple/.coverage/lcov.info
- Out html
export coverage using the following format [ html ] options [ { path: '/tmp/meteor-coverage-app-exemple/bare-exemple/.coverage',
  verbose: true } ]
Write asset: ./base.css
Write asset: ./block-navigation.js
Write asset: ./sort-arrow-sprite.png
Write asset: ./sorter.js
Write asset: ./prettify.css
Write asset: ./prettify.js
Try to remove the content & create the file /tmp/meteor-coverage-app-exemple/bare-exemple/.coverage/index.html
Creating a new html report /tmp/meteor-coverage-app-exemple/bare-exemple/.coverage/client/hey.js.html
Creating a new folder /tmp/meteor-coverage-app-exemple/bare-exemple/.coverage/client
Try to remove the content & create the file /tmp/meteor-coverage-app-exemple/bare-exemple/.coverage/client/hey.js.html
Creating a new html report /tmp/meteor-coverage-app-exemple/bare-exemple/.coverage/imports/api/links/links.js.html
Creating a new folder /tmp/meteor-coverage-app-exemple/bare-exemple/.coverage/imports/api/links
Try to remove the content & create the file /tmp/meteor-coverage-app-exemple/bare-exemple/.coverage/imports/api/links/links.js.html
Creating a new html report /tmp/meteor-coverage-app-exemple/bare-exemple/.coverage/imports/api/links/links.tests.js.html
Try to remove the content & create the file /tmp/meteor-coverage-app-exemple/bare-exemple/.coverage/imports/api/links/links.tests.js.html
Creating a new html report /tmp/meteor-coverage-app-exemple/bare-exemple/.coverage/imports/api/links/methods.js.html
Try to remove the content & create the file /tmp/meteor-coverage-app-exemple/bare-exemple/.coverage/imports/api/links/methods.js.html
Creating a new html report /tmp/meteor-coverage-app-exemple/bare-exemple/.coverage/imports/api/links/methods.tests.js.html
Try to remove the content & create the file /tmp/meteor-coverage-app-exemple/bare-exemple/.coverage/imports/api/links/methods.tests.js.html
Creating a new html report /tmp/meteor-coverage-app-exemple/bare-exemple/.coverage/imports/api/links/server/publications.js.html
Creating a new folder /tmp/meteor-coverage-app-exemple/bare-exemple/.coverage/imports/api/links/server
Try to remove the content & create the file /tmp/meteor-coverage-app-exemple/bare-exemple/.coverage/imports/api/links/server/publications.js.html
Creating a new html report /tmp/meteor-coverage-app-exemple/bare-exemple/.coverage/imports/api/links/server/publications.tests.js.html
Try to remove the content & create the file /tmp/meteor-coverage-app-exemple/bare-exemple/.coverage/imports/api/links/server/publications.tests.js.html
Creating a new html report /tmp/meteor-coverage-app-exemple/bare-exemple/.coverage/server/hey.js.html
Creating a new folder /tmp/meteor-coverage-app-exemple/bare-exemple/.coverage/server
Try to remove the content & create the file /tmp/meteor-coverage-app-exemple/bare-exemple/.coverage/server/hey.js.html

> bare-exemple@ test:packages:coverage /tmp/meteor-coverage-app-exemple/bare-exemple
> TEST_BROWSER_DRIVER=puppeteer COVERAGE=1 COVERAGE_OUT_HTML=1 COVERAGE_APP_FOLDER=$(pwd)/ meteor test-packages --once --driver-package=meteortesting:mocha --raw-logs

[[[[[ Tests ]]]]]                             

=> Started proxy.                             
local-test:cgalvarez:school: updating npm dependencies -- chai, sinon,
sinon-chai...
local-test:somepkg: updating npm dependencies -- chai, chai-as-promised...
=> Started MongoDB.                           
Module load hook: transform [/tmp/meteor-test-run12kspbt.lovl/.meteor/local/build/programs/server/packages/cgalvarez_school.js]
Module load hook: transform [/tmp/meteor-test-run12kspbt.lovl/.meteor/local/build/programs/server/packages/local-test_cgalvarez_school.js]
Module load hook: transform [/tmp/meteor-test-run12kspbt.lovl/.meteor/local/build/programs/server/packages/somepkg.js]
Module load hook: transform [/tmp/meteor-test-run12kspbt.lovl/.meteor/local/build/programs/server/packages/local-test_somepkg.js]
Module load hook: transform [app/global-imports.js]

--------------------------------
----- RUNNING SERVER TESTS -----
--------------------------------



  TypeScript school package
=> Started your app.

=> App running at: http://localhost:3000/
    ✓ creates empty Hogwarts
    ✓ enrolls Harry Potter

  my package
    ✓ run some mocha test


  3 passing (41ms)


--------------------------------
----- RUNNING CLIENT TESTS -----
--------------------------------
HeadlessChrome/73.0.3679.0


  my package
    ✓ run some mocha test


  1 passing (8ms)

Meteor-coverage is saving client side coverage to the server. Client js files saved  {"SUCCESS":50,"FAILED":0,"TOTAL":50}
All tests finished!

--------------------------------
SERVER FAILURES: 0
CLIENT FAILURES: 0
--------------------------------
```

**Comment by geoffcorey** [comment]
Hmmm, let me try installing a Linux VM and try it

**Comment by geoffcorey** [comment]
Well I'm at a loss.

```

✔ 19:43 ~/src/github.com/meteor-coverage-app-exemple/bare-exemple [master|✚ 1] $ export COVERAGE_DEBUG=1
✔ 19:43 ~/src/github.com/meteor-coverage-app-exemple/bare-exemple [master|✚ 1] $ rm -fr .coverage
✔ 19:43 ~/src/github.com/meteor-coverage-app-exemple/bare-exemple [master|✚ 1] $ uname -a
Linux gwcorey 4.18.0-13-generic #14-Ubuntu SMP Wed Dec 5 09:04:24 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
✔ 19:43 ~/src/github.com/meteor-coverage-app-exemple/bare-exemple [master|✚ 1] $ meteor npm run test:unit:coverage

> bare-exemple@ test:unit:coverage /home/gwcorey/src/github.com/meteor-coverage-app-exemple/bare-exemple
> TEST_BROWSER_DRIVER=puppeteer COVERAGE=1 COVERAGE_VERBOSE=1 COVERAGE_OUT_HTML=1 COVERAGE_OUT_LCOVONLY=1 COVERAGE_APP_FOLDER=$(pwd)/ meteor test --once --driver-package meteortesting:mocha --raw-logs

[[[[[ Tests ]]]]]

=> Started proxy.
=> Started MongoDB.
Coverage active
Reading custom configuration
[Configuration]  { include: [ '**/*.js' ],
  remap:
   { format:
      [ 'html',
        'clover',
        'cobertura',
        'json',
        'json-summary',
        'lcovonly',
        'teamcity',
        'text',
        'text-summary' ] } }
Loading default configuration: output
Loading default configuration: remapFormat
Coverage configuration:
- IS_COVERAGE_ACTIVE= true
- IS_COVERAGE_VERBOSE= true
- COVERAGE_APP_FOLDER= /home/gwcorey/src/github.com/meteor-coverage-app-exemple/bare-exemple/
.coverage.json values:
- remapFormat= [ 'html',
  'cobertura',
  'clover',
  'json',
  'json-summary',
  'lcovonly',
  'teamcity',
  'text',
  'text-summary' ]
- COVERAGE_EXPORT_FOLDER= ./.coverage

--------------------------------
----- RUNNING SERVER TESTS -----
--------------------------------



  links publications
=> Started your app.

=> App running at: http://localhost:3000/
    links.all
      ✓ sends all links

  links collection
    ✓ insert correctly

  links methods
    ✓ can add a new link

  fake testing the back
    ✓ dumb test
    ✓ should import file


  5 passing (99ms)


--------------------------------
----- RUNNING CLIENT TESTS -----
--------------------------------
HeadlessChrome/73.0.3679.0


  fake testing the front
    ✓ dumb test
    ✓ should import file


  2 passing (29ms)

Meteor-coverage is saving client side coverage to the server. Client js files saved  {"SUCCESS":0,"FAILED":0,"TOTAL":0}
All tests finished!

--------------------------------
SERVER FAILURES: 0
CLIENT FAILURES: 0
--------------------------------
Export code coverage
- Out lcovonly
export coverage using the following format [ lcovonly ] options [ { path: '/home/gwcorey/src/github.com/meteor-coverage-app-exemple/bare-exemple/.coverage',
  verbose: true } ]
Try to remove the content & create the file /home/gwcorey/src/github.com/meteor-coverage-app-exemple/bare-exemple/.coverage/lcov.info
Error: Failed to save lcovonly coverage
    at HTTP.get (packages/meteortesting:mocha/server.handleCoverage.js:37:18)
    at runWithEnvironment (packages/meteor.js:1356:24)
```

**Comment by geoffcorey** [comment]
Only other item may be different is when I try to run test:unit:coverage meteor said I needed to install the following:

```bash
meteor npm install --save chai
meteor npm install --save @babel/runtime
meteor npm install --save-dev puppeteer@^1.5.0
```

**Comment by serut** [comment]
hmm, you should run `meteor npm install` before executing tests, but I'm not sure if it will fix things.

Try to do the same than me : 
```
cd meteor-coverage-app-exemple/bare-exemple/
meteor npm install && meteor npm run test:coverage
```

**Comment by geoffcorey** [comment]
Ok getting closer!

On OS/X I did a fresh meteor install, just in case . . . 

`meteor npm run test:coverage`
* Ubuntu - Works
* OS/X  not using home directory - Works
* OS/X using home directory - Error

Also I was trying in previous steps to do `meteor npm run test:unit:coverage` and all 3 scenarios fail.
So improvement!  Not sure `test:unit:coverage` task fails but `test:coverage` works since it calls `test:unit:coverage`.

Looks like the `@` symbol in the home directory name is having some negative effect.

**Comment by serut** [comment]
So the problem was to not execute `meteor npm install` before running tests ?

Yeah nobody use an `@` in the path to a workspace :stuck_out_tongue_winking_eye:

**Comment by geoffcorey** [comment]
Yes.  3 issues -
* @ symbol in the dir name is dumb (I didn't have a choice)
* Not executing meteor npm install first
* Doing `meteor npm run test:unit:coverage` instead of `meteor npm run test:coverage`.  Still not sure why this is.

I suppose we can close this issue and chalk it up to user error! 😃 Thank you for your help!

**Comment by serut** [comment]
> * Doing `meteor npm run test:unit:coverage` instead of `meteor npm run test:coverage`.  Still not sure why this is.

Nope, there is just one command that runs the others. There is no side effect or whatever linked to this. This is just the `meteor npm install`  that saved you.

Can you create an issue on the [right issue tracker](https://github.com/serut/meteor-coverage/issues)  for the `@` issue ? I do not think I will solve it right now but maybe it can help somebody else :)

I close this issue, but if you have any other question, feel free to ask it here.

**Comment by geoffcorey** [comment]
So I was about to write up the new issue and reproduce the steps and now it is working in the base home directory with @ symbol in path.   May have to do an exorcism on my machine . . .

**Comment by geoffcorey** [comment]
The difference is I closed, updated iTerm and opened a new window.   I suspect I had a export variable that was interfering that is now no longer set.

**Comment by serut** [comment]
Shit happens ! 🥇
