### ISSUE TITLE
Couldn't run sample app's code coverage

### ISSUE THREAD

**Issue by wilcraig** [serut/meteor-coverage-app-exemple#7]
I'm trying to get code coverage working in my meteor app, but I'm having some problems. So I cloned the sample app to see if I could figure out what was breaking or incorrectly configured, and it breaks on me as well. Here's the npm-debug log:
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files (x86)\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'test:app' ]
2 info using npm@2.14.12
3 info using node@v4.3.1
4 verbose run-script [ 'pretest:app', 'test:app', 'posttest:app' ]
5 info pretest:app @
6 info test:app @
7 verbose unsafe-perm in lifecycle true
8 info @ Failed to exec test:app script
9 verbose stack Error: @ test:app: `meteor npm run coverage-app-unit && meteor npm run coverage-app-full && meteor npm run coverage-packages`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\lib\utils\lifecycle.js:214:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:821:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid @
11 verbose cwd C:\Users\ryan\Documents\GitHub\meteor-coverage-app-exemple
12 error Windows_NT 10.0.14393
13 error argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "test:app"
14 error node v4.3.1
15 error npm  v2.14.12
16 error code ELIFECYCLE
17 error @ test:app: `meteor npm run coverage-app-unit && meteor npm run coverage-app-full && meteor npm run coverage-packages`
17 error Exit status 1
18 error Failed at the @ test:app script 'meteor npm run coverage-app-unit && meteor npm run coverage-app-full && meteor npm run coverage-packages'.
18 error This is most likely a problem with the  package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     meteor npm run coverage-app-unit && meteor npm run coverage-app-full && meteor npm run coverage-packages
18 error You can get their info via:
18 error     npm owner ls
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]
```
I've tried to research this lifecycle.js error without success so far. Any help you can offer would be very much appreciated.

**Comment by serut** [comment]
Thanks for your report @wilcraig!
Indeed, nothing is working as expected on windows. I tryed to create a new `meteor-mocha` and `spacejam-mocha` cli to automatically setup `--driver-package=practicalmeteor:mocha-console-runner` to the command (inside `package.json`). https://github.com/serut/spacejam/blob/windows-suppport-rc4/bin/spacejam-mocha#L8-L10 for example

Can you try to replace `(meteor|spacejam)-mocha` into `(meteor|spacejam) --driver-package=practicalmeteor:mocha-console-runner` ?

**Comment by wilcraig** [comment]
Definitely got farther today and the first of the commands worked! Here's the npm-debug output as well as console output. Additionally, if I re-open the command prompt I seem to get different output as if I run the same command 2x in a row. I also get a single file (Icov.info) in my .coverage folder but nothing else. Also, not sure if this will help, but after it is finished running I can go to localhost:4096 and get the mocha title, or localhost:4096/coverage and see code coverage for the app. I think this indicates that a process isn't being killed correctly. maybe I just need to update the npm scripts to use different ports with each command? Also, is there a way (or need) to update these commands to run with a settings.json file?

npm-debug:

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files (x86)\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'test:app' ]
2 info using npm@2.14.12
3 info using node@v4.3.1
4 verbose run-script [ 'pretest:app', 'test:app', 'posttest:app' ]
5 info pretest:app @
6 info test:app @
7 verbose unsafe-perm in lifecycle true
8 info @ Failed to exec test:app script
9 verbose stack Error: @ test:app: `meteor npm run coverage-app-unit && meteor npm run coverage-app-full && meteor npm run coverage-packages`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\lib\utils\lifecycle.js:214:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:821:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid @
11 verbose cwd C:\Users\ryan\Documents\GitHub\meteor-coverage-app-exemple
12 error Windows_NT 10.0.14393
13 error argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "test:app"
14 error node v4.3.1
15 error npm  v2.14.12
16 error code ELIFECYCLE
17 error @ test:app: `meteor npm run coverage-app-unit && meteor npm run coverage-app-full && meteor npm run coverage-packages`
17 error Exit status 1
18 error Failed at the @ test:app script 'meteor npm run coverage-app-unit && meteor npm run coverage-app-full && meteor npm run coverage-packages'.
18 error This is most likely a problem with the  package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     meteor npm run coverage-app-unit && meteor npm run coverage-app-full && meteor npm run coverage-packages
18 error You can get their info via:
18 error     npm owner ls
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

console output:

C:\Users\ryan\Documents\GitHub\meteor-coverage-app-exemple>npm run test:app

> @ test:app C:\Users\ryan\Documents\GitHub\meteor-coverage-app-exemple
> meteor npm run coverage-app-unit && meteor npm run coverage-app-full && meteor npm run coverage-packages


> @ coverage-app-unit C:\Users\ryan\Documents\GitHub\meteor-coverage-app-exemple
> spacejam --driver-package=practicalmeteor:mocha-console-runner test --coverage 'out_lcovonly out_coverage out_html'

spacejam: spawning meteor
[[[[[ Tests ]]]]]

=> Started proxy.
=> Started MongoDB.
spacejam: meteor mongodb is ready
=> A patch (Meteor 1.4.1.3) for your current release is available!
   Update this project now with 'meteor update --patch'.
W20161103-15:34:55.920(-6)? (STDERR) Note: you are using a pure-JavaScript implementation of bcrypt.
W20161103-15:34:56.029(-6)? (STDERR) While this implementation will work correctly, it is known to be
W20161103-15:34:56.029(-6)? (STDERR) approximately three times slower than the native implementation.
W20161103-15:34:56.030(-6)? (STDERR) In order to use the native implementation instead, run
W20161103-15:34:56.030(-6)? (STDERR)
W20161103-15:34:56.031(-6)? (STDERR)   meteor npm install --save bcrypt
W20161103-15:34:56.031(-6)? (STDERR)
W20161103-15:34:56.031(-6)? (STDERR) in the root directory of your application.
=> Started your app.

=> App running at: http://localhost:4096/
   Type Control-C twice to stop.

spacejam: meteor is ready
spacejam: spawning phantomjs.exe
phantomjs: Running tests at http://localhost:4096/local using test-in-console and coverage
W20161103-15:35:01.074(-6)? (STDERR) Cannot access C:\Users\ryan\Documents\GitHub\meteor-coverage-app-exemple\packages\meteor-coverage\client\methods.js
W20161103-15:35:01.074(-6)? (STDERR) Altered source could not be accessed: meteor://�app/packages/lmieulet:meteor-coverage/client/methods.js
There is no route for the path: /local

I20161103-15:35:03.695(-6)? MochaRunner.runServerTests: Starting server side tests with run id 3TeX6TXzW36vhfWJD
C: Lists_show renders correctly with simple data : passed

C: Todos_item renders correctly with simple data : passed

C: Todos_item renders correctly when checked : passed

C: Todos_item renders correctly when editing : passed

C: Lists_show_page renders correctly with simple data : passed

C: my module does something that should be tested : passed

S: lists mutators builds correctly from factory : passed

S: lists publications lists.public sends all public lists : passed

S: lists publications lists.private sends all owned lists : passed

S: lists methods makePrivate / makePublic makes a list private and updates the todos : passed

S: lists methods makePrivate / makePublic only works if you are logged in : passed

S: lists methods makePrivate / makePublic only works if it's not the last public list : passed

S: lists methods makePrivate / makePublic only makes the list public if you made it private : passed

S: lists methods updateName changes the name, but not if you don't have permission : passed

S: lists methods remove does not delete the last public list : passed

S: lists methods remove does not delete a private list you don't own : passed

S: lists methods rate limiting does not allow more than 5 operations rapidly : passed

S: todos leaves createdAt on update : passed

S: todos mutators builds correctly from factory : passed

S: todos publications todos.inList sends all todos for a public list : passed

S: todos publications todos.inList sends all todos for a public list when logged in : passed

S: todos publications todos.inList sends all todos for a private list when logged in as owner : passed

S: todos publications todos.inList sends no todos for a private list when not logged in : passed

W20161103-15:35:04.488(-6)? (STDERR) MochaRunner.runServerTests: failures: 0
S: todos publications todos.inList sends no todos for a private list when logged in as another user : passed


--------------------------------------------------
---------------------RESULTS----------------------
PASSED: 24
FAILED: 0
SKIPPED: 0
TOTAL: 24
--------------------------------------------------
--------------------------------------------------

Tests are ok! Meteor-coverage is saving client side coverage to the server. Client js files saved  {"SUCCESS":2,"FAILED":0,"TOTAL":2}
spacejam: phantomjs.exe exited with code: 0
spacejam: killing meteor
spacejam: meteor killed with signal: SIGTERM
spacejam: All tests have passed. Exiting.

> @ coverage-app-full C:\Users\ryan\Documents\GitHub\meteor-coverage-app-exemple
> spacejam --driver-package=practicalmeteor:mocha-console-runner test --full-app --coverage 'out_lcovonly out_coverage out_html in_coverage'

spacejam: spawning meteor
Can't listen on port 4096. Perhaps another Meteor is running?

Running two copies of Meteor in the same application directory
will not work. If something else is using port 4096, you can
specify an alternative port with --port <port>.
spacejam: meteor exited with code: 254
spacejam: meteor is crashing server side. Exiting.

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Users\\ryan\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.1_1\\mt-os.windows.x86_32\\dev_bundle\\bin\\node.exe" "C:\\Users\\ryan\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.1_1\\mt-os.windows.x86_32\\dev_bundle\\lib\\node_modules\\npm\\bin\\npm-cli.js" "run" "coverage-app-full"
npm ERR! node v4.5.0
npm ERR! npm  v3.10.6
npm ERR! code ELIFECYCLE
npm ERR! @ coverage-app-full: `spacejam --driver-package=practicalmeteor:mocha-console-runner test --full-app --coverage 'out_lcovonly out_coverage out_html in_coverage'`
npm ERR! Exit status 3
npm ERR!
npm ERR! Failed at the @ coverage-app-full script 'spacejam --driver-package=practicalmeteor:mocha-console-runner test --full-app --coverage 'out_lcovonly out_coverage out_html in_coverage''.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     spacejam --driver-package=practicalmeteor:mocha-console-runner test --full-app --coverage 'out_lcovonly out_coverage out_html in_coverage'
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\ryan\Documents\GitHub\meteor-coverage-app-exemple\npm-debug.log

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "test:app"
npm ERR! node v4.3.1
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE
npm ERR! @ test:app: `meteor npm run coverage-app-unit && meteor npm run coverage-app-full && meteor npm run coverage-packages`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ test:app script 'meteor npm run coverage-app-unit && meteor npm run coverage-app-full && meteor npm run coverage-packages'.
npm ERR! This is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     meteor npm run coverage-app-unit && meteor npm run coverage-app-full && meteor npm run coverage-packages
npm ERR! You can get their info via:
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\ryan\Documents\GitHub\meteor-coverage-app-exemple\npm-debug.log
```

**Comment by serut** [comment]
Yes you're right the server (mongodb or node js) was not killed correctly and the second app (test full-app) failed to start. I need to test on windows, but nethertheless it shall works on Continuous integration, whereas on your computer you can start each type of test manually.

**Comment by serut** [comment]
V3 is out.
